/**
 * Book Rentals API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BookUpdateRequestDto { 
    name?: string | null;
    author?: string | null;
    isbn?: string | null;
    status?: boolean | null;
}

