/**
 * Book Rentals API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ClientUpdateRequestDto { 
    names?: string | null;
    lastNames?: string | null;
    dni?: string | null;
    age?: number | null;
}

