/**
 * Book Rentals API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ClientResponseDto } from './clientResponseDto';


export interface OrderByBookResponseDto { 
    id: string;
    registerTime: string;
    status: boolean;
    client: ClientResponseDto;
}

